apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome to BeCloud with Bedoya!</title>
    </head>
    <body>
        <h1>Hello from Becloud with Bedoya!</h1>
    </body>
    </html>
